"""Add association fields to User

Revision ID: 1225b9c001da
Revises: ba5d112554a9
Create Date: 2025-08-22 19:53:09.753156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1225b9c001da'
down_revision = 'ba5d112554a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('iban', sa.String(length=34), nullable=True))
        batch_op.add_column(sa.Column('official_docs', sa.String(length=255), nullable=True))
        batch_op.alter_column('photo_filename',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('photo_filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('official_docs')
        batch_op.drop_column('iban')
        batch_op.drop_column('website')
        batch_op.drop_column('logo_filename')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
