"""add cascade delete to event-participation

Revision ID: 14a65a014733
Revises: 522afd76013c
Create Date: 2025-10-07 22:32:38.238916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a65a014733'
down_revision = '522afd76013c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_option_poll_id'))

    op.drop_table('poll_option')
    with op.batch_alter_table('poll_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_vote_poll_id'))
        batch_op.drop_index(batch_op.f('ix_poll_vote_volunteer_id'))

    op.drop_table('poll_vote')
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_post_id'))

    op.drop_table('poll')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_post_id'), ['post_id'], unique=False)

    op.create_table('poll_vote',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('poll_id', sa.INTEGER(), nullable=False),
    sa.Column('volunteer_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'volunteer_id', name=op.f('uq_poll_vote_unique'))
    )
    with op.batch_alter_table('poll_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_vote_volunteer_id'), ['volunteer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poll_vote_poll_id'), ['poll_id'], unique=False)

    op.create_table('poll_option',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('poll_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=255), nullable=False),
    sa.Column('votes_count', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_option_poll_id'), ['poll_id'], unique=False)

    # ### end Alembic commands ###
