"""add petitions tables

Revision ID: 522afd76013c
Revises: b0f2e5e985c3
Create Date: 2025-09-28 17:08:06.847132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522afd76013c'
down_revision = 'b0f2e5e985c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('petition_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['petition_id'], ['petitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('petition_supports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petition_id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('supported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['association_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['petition_id'], ['petitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petition_supports')
    op.drop_table('petition_signatures')
    op.drop_table('petitions')
    # ### end Alembic commands ###
