"""add post_id to notification with FK

Revision ID: b0f2e5e985c3
Revises: a24713ad400d
Create Date: 2025-09-02 12:39:39.055781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f2e5e985c3'
down_revision = 'a24713ad400d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notification_post_id', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_post_id', type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
