"""initial schema

Revision ID: ba5d112554a9
Revises: 
Create Date: 2025-08-22 18:03:12.045265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5d112554a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_filename', sa.String(length=100), nullable=True),
    sa.Column('disponibilita', sa.Text(), nullable=True),
    sa.Column('consenso_dati', sa.Boolean(), nullable=False),
    sa.Column('accetta_termini', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('goal_amount', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_association_id'), ['association_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_duration'), ['duration'], unique=False)
        batch_op.create_index('ix_campaign_duration_dates', ['duration', 'date', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_end_date'), ['end_date'], unique=False)
        batch_op.create_index('ix_campaign_geo', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_updated_at'), ['updated_at'], unique=False)

    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id', name='_user_pair_uc')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('activity', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('capacity_max', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['association_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_activity'), ['activity'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_association_id'), ['association_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_duration'), ['duration'], unique=False)
        batch_op.create_index('ix_event_duration_date', ['duration', 'date'], unique=False)
        batch_op.create_index('ix_event_geo', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_updated_at'), ['updated_at'], unique=False)

    op.create_table('follows',
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('volunteer_id', 'association_id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_user_id'), ['user_id'], unique=False)

    op.create_table('participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volunteer_id', 'event_id', name='uq_participation_unique')
    )
    with op.batch_alter_table('participation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participation_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participation_volunteer_id'), ['volunteer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participation_volunteer_id'))
        batch_op.drop_index(batch_op.f('ix_participation_event_id'))

    op.drop_table('participation')
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_user_id'))
        batch_op.drop_index(batch_op.f('ix_donation_created_at'))
        batch_op.drop_index(batch_op.f('ix_donation_campaign_id'))

    op.drop_table('donation')
    op.drop_table('report')
    op.drop_table('post')
    op.drop_table('follows')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_updated_at'))
        batch_op.drop_index(batch_op.f('ix_event_type'))
        batch_op.drop_index('ix_event_geo')
        batch_op.drop_index('ix_event_duration_date')
        batch_op.drop_index(batch_op.f('ix_event_duration'))
        batch_op.drop_index(batch_op.f('ix_event_date'))
        batch_op.drop_index(batch_op.f('ix_event_created_at'))
        batch_op.drop_index(batch_op.f('ix_event_association_id'))
        batch_op.drop_index(batch_op.f('ix_event_activity'))

    op.drop_table('event')
    op.drop_table('chats')
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_updated_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_location'))
        batch_op.drop_index('ix_campaign_geo')
        batch_op.drop_index(batch_op.f('ix_campaign_end_date'))
        batch_op.drop_index('ix_campaign_duration_dates')
        batch_op.drop_index(batch_op.f('ix_campaign_duration'))
        batch_op.drop_index(batch_op.f('ix_campaign_date'))
        batch_op.drop_index(batch_op.f('ix_campaign_created_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_association_id'))

    op.drop_table('campaign')
    op.drop_table('user')
    # ### end Alembic commands ###
