"""add polls and applause tables

Revision ID: f73736addd9c
Revises: 5a178e830280
Create Date: 2025-08-31 23:39:29.151127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73736addd9c'
down_revision = '5a178e830280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'volunteer_id', name='uq_post_applause_unique')
    )
    with op.batch_alter_table('applause', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applause_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applause_volunteer_id'), ['volunteer_id'], unique=False)

    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_post_id'), ['post_id'], unique=False)

    op.create_table('poll_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('votes_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_option_poll_id'), ['poll_id'], unique=False)

    op.create_table('poll_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'volunteer_id', name='uq_poll_vote_unique')
    )
    with op.batch_alter_table('poll_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_vote_poll_id'), ['poll_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poll_vote_volunteer_id'), ['volunteer_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_user_type'), ['user_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_user_type'))

    with op.batch_alter_table('poll_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_vote_volunteer_id'))
        batch_op.drop_index(batch_op.f('ix_poll_vote_poll_id'))

    op.drop_table('poll_vote')
    with op.batch_alter_table('poll_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_option_poll_id'))

    op.drop_table('poll_option')
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_post_id'))

    op.drop_table('poll')
    with op.batch_alter_table('applause', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applause_volunteer_id'))
        batch_op.drop_index(batch_op.f('ix_applause_post_id'))

    op.drop_table('applause')
    # ### end Alembic commands ###
